// <auto-generated />
using Cardence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cardence.Infrastructure.Migrations
{
    [DbContext(typeof(CardenceDbContext))]
    [Migration("20260625210000_AddCardInteractions")]
    public partial class AddCardInteractions
    {
    }
}
